= Шоу, где поют

В "Шоу, где поют" приходят участники и исполняют песни.
Класс `Performance` описывает выступление: оно содержит имя участника и название песни

После выступления судьи подводят итоги: дают свои оценки и комментарии.
Абстрактный класс `Judge` моделирует судью, а класс `Judgement` -- заключение

== Задача

. Понять, что такое полиморфизм.
. Добавить в программу несколько судей.
Каждый из них по-разному оценивает участников.
Примеры:
.. Судье «А» нравятся песни Radiohead, поэтому он ставит всем, кто их исполняет 5 из 5, а остальным -- 3 из 5.
.. У судьи «Б» всегда хорошее настроение, поэтому она просто так ставит всем 5 из 5.
. Изменить класс `SongPerformanceShow`:
.. Добавить судей в массив `judges`.
.. Добавить несколько выступлений в массив `performances`.

[#submit]
== Куда сдавать

Куда удобно:

* *Slack*: отправить в личные сообщения
* *Почта*: mailto:dzavedeev@hse.ru[]

== Как скачать проект

* Если немного знаете про Git, то:
+
[source,shell script]
----
git clone https://github.com/diligent-snail/song-performance.git
----
* Если нет, то скачайте архивом:
. Code
. Download ZIP

== Как открыть проект

В Intellij IDEA:

. File
. Open
. Выберите директорию с проектом

== Как сдать проект

. Экспортируйте проект, для этого в Intellij IDEA:
.. File
.. Export
.. Project to ZIP file
. <<submit,Отправьте на проверку>>
